### PR TITLE
Features/hdf 18 halo rewards apy

### PR DESCRIPTION
**Pull request by ernestpascual**
## Description of Changes

- added the current version of the halohalo abi
- update useHaloHalo hook to fetch the current APY of halohalo
- updated the index of the staking page with the current APY and balances in 2 decimal points

Note: Instead of a helper function I integrated it as an update to the current useHaloHalo hook

[Link to Jira Ticket  -  HDF 18](https://halodao.atlassian.net/browse/HDF-18)

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
* [x] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

### CODE REVIEW

**Review by tracyarciaga — CHANGES_REQUESTED** [review]
@ernestpascual 
1.  Please change REACT_APP_HALOCHEST_ADDRESS_KOVAN  ->  REACT_APP_HALOHALO_ADDRESS_KOVAN
2. Add REACT_APP_HALOHALO_ADDRESS_KOVAN to env.example

**Comment by ernestpascual** [comment]
Updated this PR:
- changed haloChest and xHalo references to halohalo
- displayed current halo - halohalo price
- replace halochest in .env.example

**Comment by ernestpascual** [comment]
@tracyarciaga  the value did not change for you a while ago because it was too little. I think I set the current price value so high so it changes the ratio. of the conversion. Currently, 1 HALOHALO is equal to ~104,957.00 HALO. The function is still working so I added the price in the copy as reference. hope that settles it :)

**Comment by tracyarciaga** [comment]
> @tracyarciaga the value did not change for you a while ago because it was too little. I think I set the current price value so high so it changes the ratio. of the conversion. Currently, 1 HALOHALO is equal to ~104,957.00 HALO. The function is still working so I added the price in the copy as reference. hope that settles it :)

Ok  goit!  Yeah then  my only concern isthe env variable then this PR approved on my  end.

**Comment by schystz** [comment]
@ernestpascual the implementations on `useHaloHalo` looks fine! Code changes looks good in general 👍👍

Just wondering what are the addresses you used locally to test this? Because currently the preview site (https://dev-app-halodao--pr14-features-hdf-13-halo-3h215evi.web.app/#/stake) is showing "0% APY" & "1 HALOHALO is equal to 0 HALO", so I thought we just probably need to updated the addresses.

**Comment by ernestpascual** [comment]
updated env file in 1password @tracyarciaga  @schystz . well technically the same just different key

**Comment by ernestpascual** [comment]
> @ernestpascual
> 
> 1. Please change REACT_APP_HALOCHEST_ADDRESS_KOVAN  ->  REACT_APP_HALOHALO_ADDRESS_KOVAN
> 2. Add REACT_APP_HALOHALO_ADDRESS_KOVAN to env.example

because i changed this

**Comment by ernestpascual** [comment]
merged chagnes from develop

**Review by schystz — APPROVED** [review]
Implementation code looks good to me (can't say much about the underlying computations on the contract though). The APY and HALO:HALOHALO ratio also shows up fine in the preview site now so approving!

**Comment by chris247474** [comment]
Trying it now! I get this when a tx is pending (i guess theres some refresh thing happening on the UI) @ernestpascual @schystz 
image

**Comment by schystz** [comment]
> Trying it now! I get this when a tx is pending (i guess theres some refresh thing happening on the UI) @ernestpascual @schystz
> image

Oh yeah, I kind of noticed this too earlier. Could it have been overwritten by the UI tweaks @tracyarciaga ?

**Comment by chris247474** [comment]
triggering enter and leave via the UI works perfectly for me! checking the APY equation now

Edit:
I just realised the APY is calculated in the contract. I guess thats all my comments, looks great @ernestpascual well done! Just that white ui element up there that @schystz reproduced ^^ otherwise all good

**Review by tracyarciaga — APPROVED** [review]

**Pull request closed without merging**
