### PR TITLE
Feature/hdf 101 manage section

### PR DESCRIPTION
**Pull request by barryhalo**
This is the same PR as this [PR from Fork](https://github.com/HaloDAO/halodao-interface/pull/15), please refer for reference

Only difference is the PR's feature branch is from the main repo

### CODE REVIEW

**Comment by barryhalo** [comment]
@schystz eslint warnings has been fixed

**Comment by schystz** [comment]
The pool page is looking pretty good @barryhalo! Please refer to below image for my UI feedback:

ui-feedback

**Comment by barryhalo** [comment]
> The pool page is looking pretty good @barryhalo! Please refer to below image for my UI feedback:
> 
> ui-feedback

@schystz 
Got it, for Manage and Close, is what's in the design for 2.0, but yeah it's redundant when expanded

Screen Shot 2021-04-15 at 9 46 38 PM

**Comment by tracyarciaga** [comment]
> > The pool page is looking pretty good @barryhalo! Please refer to below image for my UI feedback:
> > ui-feedback
> 
> @schystz
> Got it, for Manage and Close, is what's in the design for 2.0, but yeah it's redundant when expanded
> 
> Screen Shot 2021-04-15 at 9 46 38 PM

@schystz @barryhalo about the redundancy of manage and close button, the way I understand it when looking at the Figma board, it's not redundant, but we need to hide the details from the main row when card is expanded. In the code, we need to hide the elements from this row:
https://github.com/HaloDAO/halodao-interface/blob/feature/hdf-101-manage-section/src/components/PositionCard/BalancerPoolCard.tsx#L300
to this row:
https://github.com/HaloDAO/halodao-interface/blob/feature/hdf-101-manage-section/src/components/PositionCard/BalancerPoolCard.tsx#L349

See image  below:


image

**Comment by tracyarciaga** [comment]
This is new  one from Jofo:
Decrease padding-top in manage pool card 

image

**Comment by barryhalo** [comment]
Possible new design on pool records and their titles, waiting for the final decision from @tracyarciaga and Jofo

**Comment by barryhalo** [comment]
> The pool page is looking pretty good @barryhalo! Please refer to below image for my UI feedback:
> 
> ui-feedback

@jam

**Comment by barryhalo** [comment]
> > > The pool page is looking pretty good @barryhalo! Please refer to below image for my UI feedback:
> > > ui-feedback
> > 
> > 
> > @schystz
> > Got it, for Manage and Close, is what's in the design for 2.0, but yeah it's redundant when expanded
> > Screen Shot 2021-04-15 at 9 46 38 PM
> 
> @schystz @barryhalo about the redundancy of manage and close button, the way I understand it when looking at the Figma board, it's not redundant, but we need to hide the details from the main row when card is expanded. In the code, we need to hide the elements from this row:
> https://github.com/HaloDAO/halodao-interface/blob/feature/hdf-101-manage-section/src/components/PositionCard/BalancerPoolCard.tsx#L300
> to this row:
> https://github.com/HaloDAO/halodao-interface/blob/feature/hdf-101-manage-section/src/components/PositionCard/BalancerPoolCard.tsx#L349
> 
> See image below:
> 
> image

@tracyarciaga Copy, thanks for the clarifications

**Comment by schystz** [comment]
Sorry, the wordings I used might have caused some confusion. But basically here's how I understand the pool row states -
pool-row-states

- Edit -

Just saw Jofo's explanation video that @tracyarciaga shared. Sounds to me that it confirms the above image.

**Comment by barryhalo** [comment]
@tracyarciaga @schystz @ernestpascual ready for review again

**Comment by schystz** [comment]
Hi @barryhalo , sorry a few more UI issues I found:

feedback-desktop
feedback-mobile-1
feedback-mobile-2

Please also note Jofo is about to make some slight redesign to add the "stake BPT button" and change the text copy on the purple box. (follow https://halodao-project.slack.com/archives/C01SFGC5AQP/p1618797633009100 for further updates)

**Comment by tracyarciaga** [comment]
@barryhalo Noticed same thing as what  @schystz noticed.  Pool summary info is  displayed twice when manage is clicked in mobile screen mode.   
Looking good  though!! Especially the alignment of the pools  table.

**Comment by barryhalo** [comment]
@tracyarciaga @schystz @ernestpascual ready for review again, thanks

**Comment by tracyarciaga** [comment]
Looking great @barryhalo getting there!! One last comment  -> Alignment of bunny in mobile screen mode.
image

**Comment by barryhalo** [comment]
> Looking great @barryhalo getting there!! One last comment -> Alignment of bunny in mobile screen mode.
> image

@tracyarciaga what mobile setting are you using for this?

**Pull request merged**
