### PR TITLE
Feature/hdf 101 manage section

### PR DESCRIPTION
**Pull request by barryhalo**
## Description of Changes

- Farm redesign 2.0

[Link to Jira Ticket -  HDF 97](https://halodao.atlassian.net/browse/HDF-101)

Web
Screen Shot 2021-04-14 at 11 14 47 PM

Mobile
Screen Shot 2021-04-14 at 11 15 52 PM

### CODE REVIEW

**Comment by barryhalo** [comment]
Web
Screen Shot 2021-04-14 at 11 14 47 PM

Mobile
Screen Shot 2021-04-14 at 11 15 52 PM

**Comment by ernestpascual** [comment]
Not sure what's the best practice but it seems easy to pull branches when we make branches from this repo instead of our own github account. let me know what will be our process to this. @barryhalo  @schystz  @tracyarciaga

**Review by ernestpascual — COMMENTED** [review]
hi @barryhalo  just some minor things:

Screen Shot 2021-04-15 at 1 44 51 AM

Screen Shot 2021-04-15 at 2 30 56 AM

Quick run through for mobile and web for your reference on my end: 
https://drive.google.com/file/d/1MrICut8YsPBpm-oiIEsDXI8387X6TNQY/view

**Comment by schystz** [comment]
> Not sure what's the best practice but it seems easy to pull branches when we make branches from this repo instead of our own github account. let me know what will be our process to this. @barryhalo @schystz @tracyarciaga

Had a bried discussion with Barry about this actually so will just reiterate my take on this - we can simply create a feature branch from the same repo if its an internal project (e.g. halodao-interface, minter, emp-tools, etc). Forking the repo is not required, unless its an external project that we plan to contribute with (e.g. UMA protocol repo for adding our own PHP:DAI price feed).

**Comment by ernestpascual** [comment]
> > Not sure what's the best practice but it seems easy to pull branches when we make branches from this repo instead of our own github account. let me know what will be our process to this. @barryhalo @schystz @tracyarciaga
> 
> Had a bried discussion with Barry about this actually so will just reiterate my take on this - we can simply create a feature branch from the same repo if its an internal project (e.g. halodao-interface, minter, emp-tools, etc). Forking the repo is not required, unless its an external project that we plan to contribute with (e.g. UMA protocol repo for adding our own PHP:DAI price feed).

thanks james!

**Comment by barryhalo** [comment]
> Not sure what's the best practice but it seems easy to pull branches when we make branches from this repo instead of our own github account. let me know what will be our process to this. @barryhalo @schystz @tracyarciaga

@ernestpascual @schystz good point on easy pull, I can still create the feature branch in the main repo though even if I have a fork, so I will just add that on my flow moving forward

**Comment by barryhalo** [comment]
@tracyarciaga @schystz @ernestpascual 

Feature branch `hdf-101-manage-section` is already in the main repo

Let's just retain this PR to preserve the comments

**Comment by barryhalo** [comment]
@ernestpascual 
Fixed the Total Rewards text and balance alignment for mobile

Screen Shot 2021-04-15 at 12 05 25 PM

Screen Shot 2021-04-15 at 12 06 08 PM

**Comment by barryhalo** [comment]
@ernestpascual for the `Claim` rewards text, I can't replicate the problem on my end

Screen Shot 2021-04-15 at 12 24 01 PM

So I just explicitly defined the color on the text's parent element to make sure it's not getting the colors from other elements

Screen Shot 2021-04-15 at 12 26 17 PM

**Comment by barryhalo** [comment]
@schystz 

Changed the address' border color to balance's background color, hover color is still working

Screen Shot 2021-04-15 at 3 36 01 PM

Hover active
Screen Shot 2021-04-15 at 3 38 43 PM

**Pull request closed without merging**
